name: Build Organizacao Interna
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "Organizacao-Interna/**"

concurrency:
  group: "continuous-deployment"
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  build-ferramentas-de-ambiente:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.x

      - name: install retypeapp with dotnet tool
        run: dotnet tool install retypeapp --global

      - name: build organizacao interna
        run: retype build ./Organizacao-Interna/retype.yml --output ./public/organizacao-interna
